AWSTemplateFormatVersion: '2010-09-09'

Description: "Service Catalog Entry for Sentry Deployment CloudFormation"


Parameters:
    CloudOneAccountID:
        Description: 'The Cloud One Account ID'
        Type: String
        ConstraintDescription: 'Should be entered automatically, please check this matches'

    CloudOneOIDCProviderURL:
        Description: 'The Cloud One Provider URL'
        Type: String
        Default: cloudaccounts.trend-us-1.cloudone.trendmicro.com

    CloudOneRegion:
        Description: 'The Cloud One account region'
        Type: String
        Default: trend-us-1

    QSS3BucketName:
      AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
      ConstraintDescription: Quick Start bucket name can include numbers, lowercase
        letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
        (-).
      Default: techday-2023-1
      Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
        can include numbers, lowercase letters, uppercase letters, and hyphens (-).
        It cannot start or end with a hyphen (-).
      Type: String
      
    QSS3KeyPrefix:
      AllowedPattern: ^[0-9a-zA-Z-/._]*
      ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
        uppercase letters, hyphens (-), dots(.) and forward slash (/).
      Default: "latest/"
      Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
        can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
        forward slash (/).
      Type: String


Resources:
  CloudSentryDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CloudOneAccountID: !Ref CloudOneAccountID
        CloudOneOIDCProviderURL: !Ref CloudOneOIDCProviderURL
        CloudOneRegion: !Ref CloudOneRegion
      TemplateURL:  !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}cloud_sentry/sentry_service_catalog/SentryCloudFormation.json'


